### PR TITLE
Added PL language

### PR DESCRIPTION
**Pull request by szezilla**
Just added PL language

### CODE REVIEW

**Comment by Chefkeks** [comment]
Nice!
Especially that you did NOT forget to translate the Pokemon forms 😁

**Comment by szezilla** [comment]
i didnt forget. For polish we use english pokemon names.

Michael <notifications@github.com> schrieb am Mi. 3. Apr. 2019 um 16:06:

**Comment by Chefkeks** [comment]
Hehe :D 
I guess we should change that too and use English as fallback and remove PL and other translations since a lot of languages use the English Pokemon names

**Comment by szezilla** [comment]
I want only to have bot speaking PL. Nothing more.

**Pull request merged**
