### PR TITLE
Preliminary commit for mega support in db

### PR DESCRIPTION
**Pull request by Ninjasoturi**
Added mega support to getDB.php. I went with negative form id's for megas for now (as discussed Telegram group), but more changes are required, since having negative form id's currently breaks manual raid creation. Positive side of negative ID is that it should never collide with actual form id's used by the game and adding webhook support should be easy since the evolution name->id mapping needs to only be done in one place (getDB.php).

### CODE REVIEW

**Comment by Chefkeks** [comment]
Great PR, just...

> having negative form id's currently breaks manual raid creation

is a dealbreaker for us 😢 😭

**Comment by Ninjasoturi** [comment]
@Chefkeks Further changes made to fix issues with negative form id's.
TODO: Edit raid_from_webhook to replace form id with negated evolution id if present

**Comment by Ninjasoturi** [comment]
Full support for mega evolutions should be ready. Webhook stuff is working in my test without a problem. There might be some errors I missed when testing all the manual creation stuff. And adding translations for megas in the core would remove some php notices I'm currently getting.

**Comment by Chefkeks** [comment]
😍🤗

**Comment by Artanicus** [comment]
Tested with auto raid creation, only issue seen so far is that selecting multiple bosses does not collapse after boss is updated. This however was likely already broken before so best to ignore it for now.

Next up is testing manual creations!

**Comment by Artanicus** [comment]
Everything seems to be working nicely so let's release this to the wild. :D

**Pull request merged**
